### ISSUE TITLE
nodejs install command

### ISSUE THREAD

**Issue by portaportese** [winget-run/wingetdotrun#1]
just a small thing, on the website the command to install is

```winget install -e --id OpenJS.Nodejs```

whereas the correct one is 

```winget install -e --id OpenJS.NodeJS```

**Comment by Dragon1320** [comment]
It seems to be an issue on Microsoft's end, they have `OpenJS.Nodejs` in [some manifests](https://github.com/microsoft/winget-pkgs/blob/master/manifests/OpenJS/NodeJS/14.12.0.yaml) and `OpenJS.NodeJS` in [others](https://github.com/microsoft/winget-pkgs/blob/master/manifests/OpenJS/NodeJS/15.0.1.yaml) which is reflected on our website (we have both [Nodejs](https://winget.run/pkg/OpenJS/Nodejs) and [NodeJS](https://winget.run/pkg/OpenJS/NodeJS) classed as separate packages).

As much as I'd like to, there's not much I can do on my end to fix this.
