### ISSUE TITLE
Blizzard-Battlenet: No pacakage found matching input criteria

### ISSUE THREAD

**Issue by chazragg** [winget-run/wingetdotrun#10]
according to it here https://winget.run/pkg/Blizzard/BattleNet I should be able to install the battle.net launcher through Winget by using the commands `winget install -e --id Blizzard-battlenet`
 
but i get "No Package found matching input criteria", i have found other people online referencing installing this package but I cannot see how as it doesn't exist in the official Microsoft repository. 

am I missing something?

**Comment by OfficialEsco** [comment]
Battle.net got removed from [winget-pkgs](https://github.com/microsoft/winget-pkgs) 15 August because it does not silently install.

**Comment by Dragon1320** [comment]
Updated our db, should not show on our website anymore.

**Comment by chazragg** [comment]
for future reference where is best to report these errors other than raising GitHub issues ? there is a couple of packages I have seen these inconsistencies with.

**Comment by Dragon1320** [comment]
For now GitHub issues are good, I'll try to get to them much quicker than I did before. If you have any other suggestions on how we can handle issues, feel free to let me know.
