### ISSUE TITLE
PDFCREATOR

### ISSUE THREAD

**Issue by Gamatrox33** [winget-run/wingetdotrun#13]
Hello can you integrate pdf-creator with winget?
https://pdfcreator.fr/

**Comment by Dragon1320** [comment]
We only get package data from Microsoft's package repository. If pdf-creator is not currently in https://github.com/microsoft/winget-pkgs, you should make a pr there to add it and it will show up on our website. If it is currently in https://github.com/microsoft/winget-pkgs but it doesn't show up on our website, please reopen and we'll fix it.
