### ISSUE TITLE
Versions listed in wrong order, with oldest first

### ISSUE THREAD

**Issue by deadlydog** [winget-run/wingetdotrun#14]
Looking at [the PowerShell package](https://winget.run/pkg/Microsoft/PowerShell), it shows v6.0.0.0 as the most recent version, and that versions 6.0.1.0, 6.0.2.0, ... , 7.2.1.0 are older versions. It seems that it's sorting the versions in the reverse order, thinking that the oldest version is actually the newest.

Here's a couple screenshots showing that it lists 6.0.0.0 as the most recent version and hides newer versions.

![Old versions hidden](https://user-images.githubusercontent.com/1187140/148715578-dc3e0be0-81f0-417d-9073-eb9dff8ba02a.png)

![All versions shown](https://user-images.githubusercontent.com/1187140/148715589-e7ccfa5e-dadb-4ec5-a90a-3c51d99b5906.png)

**Comment by Dragon1320** [comment]
Thanks for letting us know, this is due to our new package manifest importer not sorting versions correctly, we'll have a fix for it soon.

**Comment by Dragon1320** [comment]
Should be fixed now. If it appears unchanged, try clearing your browser cache. If it's still an issue, feel free to re-open.
