### ISSUE TITLE
BlueStacks Installer failed with exit code: 4294967254

### ISSUE THREAD

**Issue by khewweifeng** [winget-run/wingetdotrun#21]
(1/1) Found BlueStacks [BlueStack.BlueStacks] Version 5.9.135.1001
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 4294967254

**Comment by ppvnf** [comment]
Just a friendly tip, the correct place to report Winget package issues is https://github.com/microsoft/winget-pkgs/issues

**Comment by khewweifeng** [comment]
> Just a friendly tip, the correct place to report Winget package issues is https://github.com/microsoft/winget-pkgs/issues

Hi, thanks for the info 😄

**Comment by khewweifeng** [comment]
https://github.com/microsoft/winget-pkgs/issues/83317#issue-1406160895
