### ISSUE TITLE
Winget Run down

### ISSUE THREAD

**Issue by worldmixingnet** [winget-run/wingetdotrun#28]
hi we noticed its down and love the project.  Is it hosting costs that is the issue ? 

Could you get in touch.     sales@3gi.co.uk 

Terry

**Comment by juleast** [comment]
I have also noticed that it is down. Please let us know when it will come back up thanks

**Comment by Dragon1320** [comment]
The website should be back up now.

TLDR - A DigitalOcean Kubernetes update bricked our servers so I took the opportunity to migrate to a different provider (I had been planning to do so for a while). We're now on Oracle Cloud which offers a very generous always free tier so hosting costs should be lower too.
