### ISSUE TITLE
winget.run site doesn't find package

### ISSUE THREAD

**Issue by fenomeno83** [winget-run/wingetdotrun#3]
Hi.
I've recently merged my app to winget.

If I search from command line: 

    winget search fenophoto

i get result

But if I go tu

    https://winget.run/search?query=fenophoto

I cannot find results

**Comment by pgerke** [comment]
Hi all,

It's the same for me:

`https://winget.run/search?query=odassey`  comes up empty, but `winget search odassey` yields
```
~ ❯ winget search odassey
Name    ID                  Version
-----------------------------------
Odassey PhilipGerke.Odassey 1.0.0
```
as expected.

**Comment by shahoob** [comment]
You might need to wait a bit
If it still occurs, File an issue on [https://github.com/winget-run/web/issues](https://github.com/winget-run/web/issues)

Sorry for late response

**Comment by imd** [comment]
Same for XBMCFoundation.Kodi

**Comment by numeredev** [comment]
Seems like that the database did not update itself since multiple weeks.

**Comment by Dragon1320** [comment]
Updated the package database, should work now.

**Comment by pgerke** [comment]
Confirmed, thanks! 👍
