### ISSUE TITLE
winget.run - Says "0" recently updated applications and isn't searching any apps. 

### ISSUE THREAD

**Issue by jagonzalez428** [winget-run/wingetdotrun#32]
I feel like something is going over my head. I wanted to start using https://winget.run but when I go to the site to try and grab an ID, - it says "Recently updated packages: 0 packages" on the bottom, and will not search anything, even as simple as "VLC" - I have tried different connections, browsers, etc. Unless there is a region restriction, I have no idea why there isn't anything displayed when searching.

**Comment by PixelQubed** [comment]
Im getting the same. I think the database is down? I have no idea though.

**Comment by iqfareez** [comment]
Issue still exists as of today. 

![image](https://user-images.githubusercontent.com/60868965/222374034-65562318-a26e-4c2b-8633-b1127db08386.png)

**Comment by Frxhb** [comment]
yep... even API Requests are not working...

**Comment by chewgun** [comment]
for me its not working as well, i tried powershell to search the database but no luck as well..

**Comment by MattheousDT** [comment]
Sorry everyone. This is now fixed. [Full comments here](https://github.com/winget-run/wingetdotrun/issues/33#issuecomment-1472138280)
