### ISSUE TITLE
[BUG] https://winget.run/ not working at all [BUG]

### ISSUE THREAD

**Issue by officialmmt** [winget-run/wingetdotrun#33]
It was working for a while but now not working.

![image](https://user-images.githubusercontent.com/8049929/223531913-ce4c6571-1bac-4508-a6ae-d2e90f307ec3.png)
![image](https://user-images.githubusercontent.com/8049929/223531945-ccd38e22-06db-4652-8126-3a3e7890563e.png)

**Comment by gregwen** [comment]
I came here for just this purpose. Thanks for posting

**Comment by adnanaylan** [comment]
I get the same error.

**Comment by chewgun** [comment]
same for me.. since 2 weeks nothing..

**Comment by Frxhb** [comment]
Same error. Even API Requests are not working.

**Comment by ToasterUwU** [comment]
Same here

**Comment by ahdncordeiro** [comment]
I found the https://winstall.app/apps that has the same functionality and is working.

**Comment by OmriYaHoo** [comment]
> I found the https://winstall.app/apps that has the same functionality and is working.

Thanks for the recommendation, gonna switch to this for now.
A bit weird the team behind the website hasn't noticed/ignore this issue.

It's also mentioned here - #32

**Comment by Frxhb** [comment]
> I found the https://winstall.app/apps that has the same functionality and is working.

Almost... API requests as in winget.run aren't working 😐

**Comment by griesi007** [comment]
@Dragon1320 @MattheousDT Are you aware that winget.run is down and not usable currently?

**Comment by chewgun** [comment]
Does the certificate issue from WinGet impact as well the winget.run site? https://www.bleepingcomputer.com/news/security/microsoft-winget-package-manager-failing-from-expired-ssl-certificate/

**Comment by MattheousDT** [comment]
Thanks for the ping. Didn't see this in my notifications. Currently looking into it. Will keep you posted.

**Comment by MattheousDT** [comment]
The API and website are back up. We redeployed our kubernetes cluster and freshly regenerated our database. Statistics are therefore reset.

Sorry to everyone who couldn't use the site over the last week or so. We're going to set up some tracking for this stuff (and also fixing our github notifications) so that we can be alerted if anything like this happens in the future. Soon™ we'll dig into a rewrite since our setup is overly complex and a bit fragile.
