### ISSUE TITLE
winget install -e --id Logitech.LGH

### ISSUE THREAD

**Issue by demiGod095** [winget-run/wingetdotrun#5]
Logitech Gaming Hub present on winget.run ([here](https://winget.run/pkg/Logitech/LGH)), but not found when running winget.

![image](https://user-images.githubusercontent.com/17527859/132782902-3cf21355-ec5f-46c7-9a04-f16959f3949e.png)

**Comment by OfficialEsco** [comment]
Logitech.LGH got removed from winget-pkgs 2021-06-02 because it did not install correctly/silent

**Comment by Dragon1320** [comment]
Updated our db, package should no longer show up in our listings.
