### ISSUE TITLE
TUG.TeXLive removed from winget and still showing on the website

### ISSUE THREAD

**Issue by wojdatto** [winget-run/wingetdotrun#6]
I initially created an issue in [winget-pkgs](https://github.com/microsoft/winget-pkgs/issues/27528), but the issue is with winget.run.

TeXLive was removed in [this PR](https://github.com/microsoft/winget-pkgs/pull/19989#issue-684631000), but it can be still found one the website https://winget.run/pkg/TUG/TeXLive

The effect is that the package cannot be installed:

```
❯ winget install -e --id TUG.TeXLive
No package found matching input criteria.
```

**Comment by Dragon1320** [comment]
Updated the db, should be fine now.
