### ISSUE TITLE
RStudio.RStudio - No package found matching input criteria

### ISSUE THREAD

**Issue by fabiobo2005** [winget-run/wingetdotrun#8]
I found this issue that the winget.run website is showing the wrong command 
```
winget install -e --id RStudio.RStudio
```
![image](https://user-images.githubusercontent.com/29131731/137839616-d405027f-eff5-46aa-b66c-56e5eb26ccd6.png)

The correct path to install RStudio depends on the edition:

RStudio Desktop Professional Edition RStudio.RStudio.Professional 1.4.1717-3 winget
```
winget install -e --id RStudio.RStudio.Professional
```
RStudio Desktop Open Source Edition  RStudio.RStudio.OpenSource   1.4.1717   winget
```
winget install -e --id RStudio.RStudio.OpenSource
```
Source:
https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/RStudio/RStudio

**Comment by Dragon1320** [comment]
Should work now.
