### ISSUE TITLE
No package found matching input criteria.

### ISSUE THREAD

**Issue by hubertsvk** [winget-run/wingetdotrun#9]
Hi,
I was on the page https://winget.run/pkg/Files-UWP/FilesUWP and copy link marked as "how to install" and Windows Terminal shows me this
_winget install -e --id Files-UWP.FilesUWP
No package found matching input criteria._

When I tried 
_winget search Files-uwp
No package found matching input criteria._

What I did wrong?

**Comment by OfficialEsco** [comment]
winget packages mod/maintainer here
First issue, the ID `Files-UWP.FilesUWP` outdated, the new ID is `Files-Community.Files`

Second issue, we cannot update Files UWP anymore because of dependency issues between the newer versions and windows, Files Community's current workaround (since 17 days ago) is to bundle the dependency's in a Zip which includes a powershell script for easy install.

Third issue, currently winget-cli don't support zip's.

**Comment by hubertsvk** [comment]
hello,
second problem .... I want install https://winget.run/pkg/Notepads/Notepads, I used command from box "How to install"  "winget install -e --id Notepads.Notepads" 
but something is wrong ....
PS C:\Users\xxx> winget install -e --id Notepads.Notepads
No package found matching input criteria.

...but 
PS C:\Users\XXX> winget list notepads
Name     Id                    Version Source
----------------------------------------------
Notepads JackieLiu.NotepadsApp 1.4.6.0 winget

...but
PS C:\Users\XXX> winget install --id JackieLiu.NotepadsApp
Found Notepads [JackieLiu.NotepadsApp] Version 1.4.6.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
  ██████████████████████████████  2%
Successfully installed. Restart the application to complete the upgrade.

command from box "How to install" is wrong

**Comment by hubertsvk** [comment]
and next package ... what I doing wrong? Is it problem with my system?

PS C:\Users\XXX> winget search scp -s winget
Name      Id               Version   Match
---------------------------------------------
WinSCP    WinSCP.WinSCP    5.19.5    Tag: scp
SmarTTY   Sysprogs.SmarTTY 3.2       Tag: scp
WinSCP RC WinSCP.WinSCP.RC 5.18.5-RC Tag: scp

PS C:\Users\XXX> winget install WinSCP
Found WinSCP [WinSCP.WinSCP] Version 5.19.5
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://sourceforge.net/projects/winscp/files/WinSCP/5.19.5/WinSCP-5.19.5-Setup.exe/download
An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072f0d : unknown error

**Comment by OfficialEsco** [comment]
As you noticed, Notepads got moved to `JackieLiu.NotepadsApp`. AFAIK winget.run have had internal issues for months, i would recommend checking out https://winstall.app

0x80072f0d is a issue on your end, either Windows or Network
* https://github.com/microsoft/winget-cli/issues/566

**Comment by Dragon1320** [comment]
Should work on our end now.
